name: CI-CD Pipeline
# This workflow builds a Docker ima
on:
  push:
    branches: ["main"]

jobs:
  build-test-push:
    runs-on: self-hosted

    env:
      VERSION: v1.0.${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract commit SHA
        shell: powershell
        run: |
          $sha = git rev-parse --short HEAD
          echo "SHA=$sha" >> $env:GITHUB_ENV

      - name: Debug values
        shell: powershell
        run: |
          echo "SHA is: $env:SHA"
          echo "User is: ${{ secrets.DOCKER_USERNAME }}"

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/logistics-app:${{ env.SHA }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/logistics-app:${{ env.SHA }} ${{ secrets.DOCKER_USERNAME }}/logistics-app:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/logistics-app:${{ env.SHA }} ${{ secrets.DOCKER_USERNAME }}/logistics-app:${{ env.VERSION }}

      - name: Push Docker Images
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/logistics-app:${{ env.SHA }}"
          docker push "${{ secrets.DOCKER_USERNAME }}/logistics-app:latest"
          docker push ${{ secrets.DOCKER_USERNAME }}/logistics-app:${{ env.VERSION }}

      - name: Debug image
        run: echo "${{ secrets.DOCKER_USERNAME }}/logistics-app:${{ env.SHA }}"
      
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/logistics-app logistics-app=${{ secrets.DOCKER_USERNAME }}/logistics-app:${{ env.SHA }}
          kubectl annotate deployment logistics-app kubernetes.io/change-cause="commit ${{ env.SHA }}"
          kubectl rollout status deployment/logistics-app

      - name: Cleanup Docker images
        run: |
          docker image prune -f
          docker images "${{ secrets.DOCKER_USERNAME }}/logistics-app" --format "{{.Tag}}" | grep -v "${{ env.SHA }}" | grep -v "latest" | xargs -r -I {} docker rmi ${{ secrets.DOCKER_USERNAME }}/logistics-app:{}